### PR TITLE
Bug: Expiration Date

### LINKED ISSUE #9: Bug: Payment type info is incorrect
Customers are complaining that the expiration date on their payment types are incorrect.

### PR DESCRIPTION
**Pull request by oliverkennelly**
Previously, there was no place to see the expiration date nor add one to a card. Added input and display for this!

Server side supported this already, so there was no need for any changes on that side. All that was needed was another input field for it and some formatting for the customer. 

Test by navigating to "http://localhost:3000/payments" and see the changes on the page, then add a new payment.

### CODE REVIEW

File: components/payments/payment-modal.js [hunk 1]
```diff
@@ -5,6 +5,7 @@ import Modal from "../modal"
 export default function AddPaymentModal({ showModal, setShowModal, addNewPayment }) {
   const merchantNameInput = useRef()
   const acctNumInput = useRef()
+  const expireDateInput = useRef()
```
Comment (novofeels) [inline components/payments/payment-modal.js]: I'd suggest using state to manage these instead of ref as per steves reccomendations

File: components/payments/payment-modal.js [hunk 2]
```diff
@@ -20,13 +21,21 @@ export default function AddPaymentModal({ showModal, setShowModal, addNewPayment
...
       </>
       <>
         <button
           className="button is-success"
           onClick={() => addNewPayment({
-            acctNumber: acctNumInput.current.value,
-            merchant: merchantNameInput.current.value
+            account_number: acctNumInput.current.value,
+            merchant_name: merchantNameInput.current.value,
+            expiration_date: `${expireDateInput.current.value}-01`,
```
Comment (novofeels) [inline components/payments/payment-modal.js]: for me right now whatever year i have put in here, it posts 2024 regardless.

**Review by novofeels — CHANGES_REQUESTED** [review]

File: components/payments/payment-modal.js (hunk 2 above)
Comment (carsonruscin) [reply components/payments/payment-modal.js]: Have the same problem as well, issue still persists.

File: components/payments/payment-modal.js (hunk 1 above)
Comment (oliverkennelly) [reply components/payments/payment-modal.js]: i agree with this, however i find that if i were to use state here that would require rewriting the rest of these to keep consistency, but if that's the standard the team wants to keep ill rewrite these too 👍

File: components/payments/payment-modal.js (hunk 2 above)
Comment (oliverkennelly) [reply components/payments/payment-modal.js]: this is actually an api issue, where create date and expiration date were mixed up. will make a pull request for this small fix 👍

**Review by novofeels — APPROVED** [review]
looks good!
